### PR TITLE
Use standard style and utilities from core-js/npm

### PR DESCRIPTION
**Pull request by bendrucker**
This is a monster one. Sorry to change so many lines here. This does two things:
1. Implements [JavaScript standard style](https://github.com/feross/standard), eliminating the need for bikeshedding about linting and manually managing rules
2. Eliminates lodash in favor of ESNext methods that Babel ponyfills (replaces the method with polluting the global scope). In a few cases I just grabbed little utilities from npm. This has the advantage of making the code dramatically easier to understand. Before there was a lot of re-application of `arguments` objects from lodash callbacks. That's super hard to understand unless you're an active lodash user.

### CODE REVIEW

**Comment by bendrucker** [comment]
I'll go back and rebase this in the cases where I grabbed something from npm and then realized that babel can ponyfill an ESNext method that does the same thing

**Comment by bendrucker** [comment]
I can get this fully rebased if you revert 7ff84673b57b84aa2c856af3f0ac68452c9ece15. Otherwise there's a bunch of extra conflicts for me to resolve for things that don't even exist anymore.

**Comment by bendrucker** [comment]
On hangouts right now if you wanna bang this out

**Comment by aputinski** [comment]
Overall, everything looks good. Thanks for all this work!

Just a few comments:
- Can you please add the `lodash` dependency back and remove:
  `clone`, `deep-extend`, and `object-pick`
- Also, I prefer the functional style of type checking, so please use `isString()` and `isNumber()` from lodash as well

**Comment by bendrucker** [comment]
Done. Lodash is a ^ dep now. They are super thorough about everything so I'd recommend leaving it as such.

**Pull request merged**
